### ISSUE TITLE
[New Package]: Alibaba.Teambition

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/winget-pkgs-automation#257]
### List the PackageIdentifier of the package to be added to automation

Alibaba.Teambition

### Details about the application

2 sources

https://im.dingtalk.com/manifest/dtron/Teambition/win32/ia32/latest.yml
Comes from updater and it's newer than the second one.
```Yaml
version: 2.0.1
files:
  - url: https://tongyongxiezuo.oss-cn-zhangjiakou.aliyuncs.com/desktop/Teambition/2.0.1/update/win32/ia32/Teambition-2.0.1-win.exe
    sha512: MSPZVnhHgj43mwm40L0sDQtEB2QtEaejcY57S0ybMl+1Y3RBiWDI4pYw2kjUJpud+BStjMYpmrx1sSIdi8lXzQ==
    size: 82303924
path: https://tongyongxiezuo.oss-cn-zhangjiakou.aliyuncs.com/desktop/Teambition/2.0.1/update/win32/ia32/Teambition-2.0.1-win.exe
sha512: MSPZVnhHgj43mwm40L0sDQtEB2QtEaejcY57S0ybMl+1Y3RBiWDI4pYw2kjUJpud+BStjMYpmrx1sSIdi8lXzQ==
releaseDate: '2021-05-20T09:48:25.397Z'
stagingPercentage: 100
```

https://www.teambition.com/site/client-config
Comes from download page.
```JSON
{"download_links":{"mac":"https://tongyongxiezuo.oss-cn-zhangjiakou.aliyuncs.com/desktop/Teambition/2.0.0/install/darwin/x64/Teambition-2.0.0-mac.dmg","pc":"https://tongyongxiezuo.oss-cn-zhangjiakou.aliyuncs.com/desktop/Teambition/2.0.0/install/win32/ia32/Teambition-2.0.0-win.exe"}}
```
