### ISSUE TITLE
[New Package]: Baidu.BaiduWenku

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/winget-pkgs-automation#260]
### List the PackageIdentifier of the package to be added to automation

Baidu.BaiduWenku

### Details about the application

https://edu-wenku.bdimg.com/v1/pcclient/upgrade/latest.yml
```Yaml
version: 1.1.2
files:
  - url: 百度文库 Setup 1.1.2.exe
    sha512: pwBIpHAuEMzUU83dLrftSVMX+JruYmV5pnC2Ir2z/TaQqt0PB+JsdYEcEAhTl7Ejd0FGFlLeC/Yrgmtx/oTyEw==
    size: 67619259
    isAdminRightsRequired: true
path: 百度文库 Setup 1.1.2.exe
sha512: pwBIpHAuEMzUU83dLrftSVMX+JruYmV5pnC2Ir2z/TaQqt0PB+JsdYEcEAhTl7Ejd0FGFlLeC/Yrgmtx/oTyEw==
releaseDate: '2021-05-11T12:52:10.232Z'

```
